load_config_path: null

model:
  model_type: Gr00tN1d7
  model_name: nvidia/Cosmos-Reason2-2B
  tune_llm: false
  tune_visual: false
  tune_projector: true
  tune_diffusion_model: true
  state_dropout_prob: 0.2
  color_jitter_params:
    brightness: 0.3
    contrast: 0.4
    saturation: 0.5
    hue: 0.08
  load_bf16: false
  reproject_vision: false
  backbone_trainable_params_fp32: true
  use_relative_action: true

data:
  datasets:
    - dataset_paths:
        - /data/liuyilong/dataset/token_only_gr00t_human_C_full_body_base_action_lead1
      embodiment_tag: unitree_g1_sonic_human
      mix_ratio: 2.0
      dataset_type: physical_embodiment
      val_dataset_path: null
    - dataset_paths:
        - /data/liuyilong/dataset/walk_and_place
      embodiment_tag: unitree_g1_sonic
      mix_ratio: 1.0
      dataset_type: physical_embodiment
      val_dataset_path: null
  download_cache: false
  shard_size: 1024
  episode_sampling_rate: 0.1
  num_shards_per_epoch: 100000
  override_pretraining_statistics: true
  mode: single_turn
  random_chop: 0.0
  mock_dataset_mode: false
  shuffle: true
  seed: 42
  multiprocessing_context: fork
  allow_padding: false
  subsample_ratio: 1.0
  image_crop_size:
    - 244
    - 244
  image_target_size:
    - 224
    - 224
  video_backend: torchcodec

training:
  output_dir: output_walk_lead1_smpllag0_diffembody
  experiment_name: null
  max_steps: 50000
  global_batch_size: 64
  batch_size: null
  gradient_accumulation_steps: 1
  learning_rate: 0.0001
  lr_scheduler_type: cosine
  weight_decay: 0.00001
  warmup_ratio: 0.05
  warmup_steps: 0
  max_grad_norm: 1.0
  optim: adamw_torch
  skip_weight_loading: false
  tf32: true
  fp16: false
  bf16: true
  eval_bf16: true
  logging_steps: 10
  save_steps: 5000
  save_total_limit: 10
  save_vl_model: false
  save_only_model: false
  upload_checkpoints: false
  eval_strategy: "no"
  deepspeed_stage: 2
  gradient_checkpointing: false
  transformers_trust_remote_code: true
  transformers_local_files_only: false
  transformers_cache_dir: null
  transformers_access_token: null
  use_ddp: false
  ddp_bucket_cap_mb: 100
  num_gpus: 8
  dataloader_num_workers: 8
  remove_unused_columns: false
  use_wandb: true
  wandb_project: finetune-gr00t-n1d7
